import { prisma } from "../lib/prisma";

const API_URL = "http://localhost:3000";

async function main() {
  console.log("🚀 Starting random seed test...");

  // 1. Generate a random Invite Code directly in DB
  const code = `TEST_${Math.random().toString(36).substring(7).toUpperCase()}`;
  console.log(`🎫 Creating invite code: ${code}`);

  try {
    await prisma.inviteCode.create({
      data: {
        code,
        isUsed: false,
      },
    });
  } catch (e) {
    console.error(
      "Error creating invite code. Ensure InviteCode table exists and prisma is generated.",
    );
    throw e;
  }

  // 2. Signup User via API
  const email = `test_${Math.random().toString(36).substring(7)}@example.com`;
  const password = "password123";

  console.log(`👤 Signing up user: ${email}`);

  const signupRes = await fetch(`${API_URL}/auth/signup`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email, password, inviteCode: code }),
  });

  if (!signupRes.ok) {
    const err = await signupRes.text();
    throw new Error(`Signup failed: ${err}`);
  }

  const authData = (await signupRes.json()) as any;
  const token = authData.data.session.access_token;
  console.log("✅ User signed up, token received.");

  // 3. Create Random Rig (Build)
  const rigName = `Rig ${Math.random().toString(36).substring(7).toUpperCase()}`;
  console.log(`🚐 Creating Rig: ${rigName}`);

  const rigRes = await fetch(`${API_URL}/builds`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      name: rigName,
      model: "Sprinter 144",
      imageUrl:
        "https://images.unsplash.com/photo-1520038410233-7141be7e6f97?q=80&w=2940&auto=format&fit=crop",
      description: "A random test build generated by script.",
      tags: ["SOLAR", "OFFGRID"],
    }),
  });

  if (!rigRes.ok) {
    const err = await rigRes.text();
    throw new Error(`Create Build failed: ${err}`);
  }
  console.log("✅ Rig created successfully.");

  // 4. Create Random Garage Entry
  const garageName = `Garage ${Math.random().toString(36).substring(7).toUpperCase()}`;
  console.log(`🔧 Creating Garage: ${garageName}`);

  const garageRes = await fetch(`${API_URL}/garage`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      name: garageName,
      title: "Master Builder",
      specialty: "Electrical",
      rate: "$100/hr",
      category: "SOLAR",
      imageUrl:
        "https://images.unsplash.com/photo-1581092921461-eab62e97a782?q=80&w=2940&auto=format&fit=crop",
      phoneNumber: "555-0199",
      email: email,
      location: "Test City, TS",
    }),
  });

  if (!garageRes.ok) {
    const err = await garageRes.text();
    throw new Error(`Create Garage failed: ${err}`);
  }
  console.log("✅ Garage profile created successfully.");

  console.log("🎉 All tests passed!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
